[book]
authors = ["Philip Zucker"]
language = "en"
multilingual = false
src = "src"
title = "Datalog Comin' Right At Ya!"


[output.html]
additional-js = ["src/souffle.wasm", "src/souffle.js", "src/custom.js"]

[output.html.playground]
editable = true
